s3_conf:
  access_key: 
  secret_access_key: 
  s3_bucket: roshith-bucket

sftp_conf:
    hostname: x.amazonaws.com
    port: 22
    username: ubuntu
    pem: resources/sftpKeyPair.ppk
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data